default: &default
  sitename: ""
  title: ""
  cn_name: "太平洋电脑"
  domain: ""
  description: "发现，流通二手电子产品"
  es_url: "http://localhost:9200"

production:
  <<: *default

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
