default: &default
  sitename: ""
  title: "Foobar"
  cn_name: "Foobar"
  domain: ""
  description: "发现，流通二手电子产品"

production:
  <<: *default

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
